### PR TITLE
add setup script for pip

### PR DESCRIPTION
**Pull request by ghost**
I would like to use this module in a project, therefore it needs to have at least a `setup.py` file in order to install it via `pip`. Nice work btw and easy to use lib!

### CODE REVIEW

**Comment by dvvc** [comment]
Thanks for the contribution, @mankoell Really glad someone is using this code!

**Comment by ghost** [comment]
@dvvc Hey, thanks for your fast response! I didn't think, this project is still alive! I was looking for a solution to parse org files and the only semi-official one I found ([PyOrgMode](https://github.com/bjonnh/PyOrgMode/tree/master/PyOrgMode)) has a really ugly API. Thanks a lot for this beauty of code!

**Comment by dvvc** [comment]
To be frank, the project is kind of in zombie state :) I am not super proud of the code because I wrote it ages ago, but knowing that people is interested definitely makes me want to go back to it and clean it up. Do you have a link to the project where you are using it? I'd love to know where this can be improved (and I'd also love any contributions you have, keep them coming!! :+1: )

**Comment by ghost** [comment]
This project still looks better than the project I mentioned above! I wanna use it to refactor a [memacs](https://github.com/novoid/Memacs) module to parse a contactsfile made with [org-contacts.el](https://julien.danjou.info/projects/emacs-packages#org-contacts). I also wanted to create my own **orgtodict** parser, which feels even more natural to use, something like [xmltodict](https://github.com/martinblech/xmltodict). But I feel more comfy with yours right now, as it mimics some builtin libraries I already worked with. So I gonna add some features I need for soon! :)

**Pull request merged**
